version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network

  dev:
    image: node:18-alpine
    container_name: vue_dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
